#include "src/include/vector3.h"
struct Target {char unknown0[32];unsigned short identifier;char unknown34[10];short category;char unknown46[14];Vector3 position;char unknown72[776];unsigned int flags;};
struct Base {char unknown0[24];
virtual void unused0();
virtual void unused1();
virtual void unused2();
virtual void unused3();
virtual void unused4();
virtual void unused5();
virtual void unused6();
virtual void unused7();
virtual void unused8();
virtual void unused9();
virtual void unused10();
virtual void unused11();
virtual void unused12();
virtual void unused13();
virtual void unused14();
virtual void unused15();
virtual void unused16();
virtual void unused17();
virtual void unused18();
virtual void unused19();
virtual void unused20();
virtual void unused21();
virtual void unused22();
virtual void unused23();
virtual void attach(Target *,float);
virtual void unused25();
virtual void unused26();
virtual void unused27();
virtual void unused28();
virtual void unused29();
virtual void unused30();
virtual void unused31();
virtual void unused32();
virtual void unused33();
virtual void unused34();
virtual void unused35();
virtual void unused36();
virtual void unused37();
virtual void unused38();
virtual void unused39();
virtual void unused40();
virtual void unused41();
virtual void unused42();
virtual void unused43();
virtual void unused44();
virtual void unused45();
virtual void unused46();
virtual void unused47();
virtual void unused48();
virtual void unused49();
virtual void unused50();
virtual void unused51();
virtual void unused52();
virtual void unused53();
virtual void unused54();
virtual void unused55();
virtual void unused56();
virtual void unused57();
virtual void unused58();
virtual void unused59();
virtual void unused60();
virtual void unused61();
virtual void unused62();
virtual void unused63();
virtual void unused64();
virtual void unused65();
virtual void unused66();
virtual void unused67();
virtual void unused68();
virtual void unused69();
virtual void unused70();
virtual void unused71();
virtual void unused72();
virtual void unused73();
virtual void unused74();
virtual void unused75();
virtual void unused76();
virtual void unused77();
virtual void unused78();
virtual void unused79();
virtual void unused80();
virtual void unused81();
virtual void unused82();
virtual void unused83();
virtual void unused84();
virtual void unused85();
virtual void state_zero();
};
struct View:Base {char unknown28[16];short category;char unknown46[14];Vector3 position;char unknown72[64];int value;char unknown140[638];short state;char unknown780[24];Vector3 anchor;char unknown816[4];Target *target;char unknown824[24];float radius,range;unsigned short identifier;char unknown858[2];int visible;};
typedef char check_base[sizeof(Base)==28?1:-1];
typedef char check_View_category[(unsigned long)&((View *)0)->category==44?1:-1];
typedef char check_View_position[(unsigned long)&((View *)0)->position==60?1:-1];
typedef char check_View_value[(unsigned long)&((View *)0)->value==136?1:-1];
typedef char check_View_state[(unsigned long)&((View *)0)->state==778?1:-1];
typedef char check_View_anchor[(unsigned long)&((View *)0)->anchor==804?1:-1];
typedef char check_View_target[(unsigned long)&((View *)0)->target==820?1:-1];
typedef char check_View_radius[(unsigned long)&((View *)0)->radius==848?1:-1];
typedef char check_View_range[(unsigned long)&((View *)0)->range==852?1:-1];
typedef char check_View_identifier[(unsigned long)&((View *)0)->identifier==856?1:-1];
typedef char check_View_visible[(unsigned long)&((View *)0)->visible==860?1:-1];
typedef char check_Target_identifier[(unsigned long)&((Target *)0)->identifier==32?1:-1];
typedef char check_Target_category[(unsigned long)&((Target *)0)->category==44?1:-1];
typedef char check_Target_position[(unsigned long)&((Target *)0)->position==60?1:-1];
typedef char check_Target_flags[(unsigned long)&((Target *)0)->flags==848?1:-1];
extern "C" {extern unsigned int current_identifier;extern Target *lookup_at(unsigned int);extern void update_at(View *);extern unsigned short find_at(View *,int,float);extern float distance_at(const Vector3 *,const Vector3 *);}
static inline int flagged(Target *o) {return (o->flags&1)!=0;}
extern "C" {extern void refresh_at(View *),affect_at(Target *),advance_at(View *);
void apply_context_target(View *o) {update_at(o);refresh_at(o);if(o->value<0) {o->attach(o->target,1.0f);if(o->target&&current_identifier==o->target->identifier) {Target *target=lookup_at(current_identifier);if(target) {int flag=flagged(target);if(flag!=0) affect_at(target);}}}if(o->visible==1) advance_at(o);}
}
