typedef struct Node {unsigned int flags;char unknown4[4];float x,y,width,height;char unknown24[8];void *active;int value;} Node;
typedef struct Pair {unsigned int flags;int remaining;} Pair;
typedef struct View {char unknown0[48];Node **nodes;unsigned int flags;char unknown56[24];float current2,current3;char unknown88[12];unsigned int field100;char unknown104[20];float offset;int first,selected,ttl;float next;Pair *pairs;float target;int insert,capacity;} View;
typedef char check_size_Node[sizeof(Node)==40?1:-1];
typedef char check_Node_flags[(unsigned long)&((Node *)0)->flags==0?1:-1];
typedef char check_Node_x[(unsigned long)&((Node *)0)->x==8?1:-1];
typedef char check_Node_y[(unsigned long)&((Node *)0)->y==12?1:-1];
typedef char check_Node_width[(unsigned long)&((Node *)0)->width==16?1:-1];
typedef char check_Node_height[(unsigned long)&((Node *)0)->height==20?1:-1];
typedef char check_Node_active[(unsigned long)&((Node *)0)->active==32?1:-1];
typedef char check_Node_value[(unsigned long)&((Node *)0)->value==36?1:-1];
typedef char check_size_Pair[sizeof(Pair)==8?1:-1];
typedef char check_Pair_flags[(unsigned long)&((Pair *)0)->flags==0?1:-1];
typedef char check_Pair_remaining[(unsigned long)&((Pair *)0)->remaining==4?1:-1];
typedef char check_size_View[sizeof(View)==160?1:-1];
typedef char check_View_nodes[(unsigned long)&((View *)0)->nodes==48?1:-1];
typedef char check_View_flags[(unsigned long)&((View *)0)->flags==52?1:-1];
typedef char check_View_current2[(unsigned long)&((View *)0)->current2==80?1:-1];
typedef char check_View_current3[(unsigned long)&((View *)0)->current3==84?1:-1];
typedef char check_View_field100[(unsigned long)&((View *)0)->field100==100?1:-1];
typedef char check_View_offset[(unsigned long)&((View *)0)->offset==124?1:-1];
typedef char check_View_first[(unsigned long)&((View *)0)->first==128?1:-1];
typedef char check_View_selected[(unsigned long)&((View *)0)->selected==132?1:-1];
typedef char check_View_ttl[(unsigned long)&((View *)0)->ttl==136?1:-1];
typedef char check_View_next[(unsigned long)&((View *)0)->next==140?1:-1];
typedef char check_View_pairs[(unsigned long)&((View *)0)->pairs==144?1:-1];
typedef char check_View_target[(unsigned long)&((View *)0)->target==148?1:-1];
typedef char check_View_insert[(unsigned long)&((View *)0)->insert==152?1:-1];
typedef char check_View_capacity[(unsigned long)&((View *)0)->capacity==156?1:-1];
void approach_pair_grid_offset(View *o) {float difference;float target=o->target;float step;difference=target-o->offset;step=difference*0.15f;if(step<15.0f) step=15.0f;if(step>difference) o->offset=target;else o->offset+=step;}
