#include "src/include/vector3.h"
struct Geometry {Vector3 position,normal;};
struct Contact {unsigned int unknown0;Geometry *geometry;};
class Base {public:char unknown0[24];
virtual void unused0();
virtual void unused1();
virtual void unused2();
virtual void unused3();
virtual void unused4();
virtual void unused5();
virtual void unused6();
virtual void unused7();
virtual void unused8();
virtual void unused9();
virtual void unused10();
virtual void unused11();
virtual void unused12();
virtual void unused13();
virtual void unused14();
virtual void unused15();
virtual void unused16();
virtual void unused17();
virtual Contact *current_contact();
virtual Contact *contact(Vector3 *);
virtual void unused20();
virtual void unused21();
virtual void unused22();
virtual void unused23();
virtual void unused24();
virtual void unused25();
virtual void unused26();
virtual void unused27();
virtual void unused28();
virtual void unused29();
virtual void unused30();
virtual void unused31();
virtual void unused32();
virtual void unused33();
virtual void unused34();
virtual void unused35();
virtual void unused36();
virtual void unused37();
virtual void unused38();
virtual void unused39();
virtual void unused40();
virtual void unused41();
virtual void unused42();
virtual void unused43();
virtual void unused44();
virtual void unused45();
virtual void unused46();
virtual void unused47();
virtual void unused48();
virtual void unused49();
virtual void unused50();
virtual void unused51();
virtual void unused52();
virtual void unused53();
virtual void unused54();
virtual void unused55();
virtual void unused56();
virtual void unused57();
virtual void unused58();
virtual void unused59();
virtual void unused60();
virtual void unused61();
virtual void unused62();
virtual void unused63();
virtual void unused64();
virtual void unused65();
virtual void unused66();
virtual void unused67();
virtual void unused68();
virtual void unused69();
virtual void unused70();
virtual void unused71();
virtual void unused72();
virtual void unused73();
virtual void unused74();
virtual void unused75();
virtual void unused76();
virtual void unused77();
virtual void unused78();
virtual void unused79();
virtual void unused80();
virtual void unused81();
virtual void unused82();
virtual void unused83();
virtual void unused84();
virtual void unused85();
virtual void unused86();
virtual void unused87();
virtual void unused88();
virtual void unused89();
virtual void unused90();
virtual void unused91();
virtual void unused92();
virtual void unused93();
virtual void unused94();
virtual void unused95();
virtual void unused96();
virtual void unused97();
virtual void unused98();
virtual void unused99();
virtual void unused100();
virtual void unused101();
virtual void unused102();
virtual void unused103();
virtual void unused104();
virtual void unused105();
virtual void unused106();
virtual Contact *apply_contact(Vector3 *);
};
class View:public Base {public:char unknown28[32];Vector3 position,previous;char unknown84[284];Vector3 normal;char unknown380[540];float radius;int blocked,failures;};
typedef char check_view[sizeof(Base)==28 && sizeof(View)==932 && (unsigned long)&((View *)0)->position==60 && (unsigned long)&((View *)0)->previous==72 && (unsigned long)&((View *)0)->normal==368 && (unsigned long)&((View *)0)->failures==928 ? 1:-1];
typedef char check_geometry[sizeof(Geometry)==24 && (unsigned long)&((Geometry *)0)->normal==12 && sizeof(Contact)==8 && (unsigned long)&((Contact *)0)->geometry==4 ? 1:-1];
typedef char check_radius[(unsigned long)&((View *)0)->radius==920 && (unsigned long)&((View *)0)->blocked==924 ? 1:-1];
extern "C" Contact *query_scaled(View *,float,float,float);
extern "C" float square_root(float);
extern "C" Contact *clamp_and_dispatch_contact(View *o,float dx,float dz,float scale) {
 Vector3 destination;
 float travel=scale;
 Contact *contact=query_scaled(o,dx,dz,o->radius+scale);
 if(!contact)o->blocked=0;
 else {
  float x,z;
  o->blocked++;
  x=contact->geometry->position.x-o->position.x;
  z=contact->geometry->position.z-o->position.z;
  travel=square_root(x*x+z*z)-o->radius;
 }
 destination.x=dx*travel+o->position.x;
 destination.y=o->position.y;
 destination.z=dz*travel+o->position.z;
 return o->apply_contact(&destination);
}
