#include "src/include/vector3.h"
struct Base {char unknown0[24];
virtual void unused0();
virtual void unused1();
virtual void unused2();
virtual void unused3();
virtual void unused4();
virtual void unused5();
virtual void unused6();
virtual void unused7();
virtual void unused8();
virtual void unused9();
virtual void unused10();
virtual int visible_at(float,float);
virtual void unused12();
virtual void unused13();
virtual void unused14();
virtual void unused15();
virtual void unused16();
virtual void unused17();
virtual void unused18();
virtual void unused19();
virtual void unused20();
virtual void unused21();
virtual void unused22();
virtual void unused23();
virtual void unused24();
virtual void unused25();
virtual void unused26();
virtual void unused27();
virtual void unused28();
virtual void unused29();
virtual void unused30();
virtual void unused31();
virtual void unused32();
virtual void unused33();
virtual void unused34();
virtual void unused35();
virtual void unused36();
virtual void unused37();
virtual void unused38();
virtual void unused39();
virtual void unused40();
virtual void unused41();
virtual void unused42();
virtual void unused43();
virtual void unused44();
virtual void unused45();
virtual void unused46();
virtual void unused47();
virtual void unused48();
virtual void unused49();
virtual void unused50();
virtual void unused51();
virtual void unused52();
virtual void unused53();
virtual void unused54();
virtual void unused55();
virtual void unused56();
virtual void unused57();
virtual void unused58();
virtual void unused59();
virtual void unused60();
virtual void unused61();
virtual void unused62();
virtual void unused63();
virtual void unused64();
virtual void unused65();
virtual void unused66();
virtual void unused67();
virtual void unused68();
virtual void unused69();
virtual void unused70();
virtual void unused71();
virtual void unused72();
virtual void unused73();
virtual void unused74();
virtual void unused75();
virtual void unused76();
virtual void unused77();
virtual void unused78();
virtual void unused79();
virtual void unused80();
virtual void unused81();
virtual void unused82();
virtual void unused83();
virtual void unused84();
virtual void unused85();
virtual void state_zero();
virtual void state_one();
virtual void state_two();
virtual void state_three();
virtual int ready();
virtual void prepare();
virtual void unused92();
virtual void special();
};
struct View:Base {char unknown28[12];void *transform;char unknown44[12];void *resource;Vector3 position;char unknown72[28];unsigned int angle;char unknown104[144];float parameter;char unknown252[52];void *context;char unknown308[470];short state;char unknown780[80];int visible;};
typedef char check_base[sizeof(Base)==28?1:-1];
typedef char check_transform[(unsigned long)&((View *)0)->transform==40?1:-1];
typedef char check_resource[(unsigned long)&((View *)0)->resource==56?1:-1];
typedef char check_position[(unsigned long)&((View *)0)->position==60?1:-1];
typedef char check_angle[(unsigned long)&((View *)0)->angle==100?1:-1];
typedef char check_parameter[(unsigned long)&((View *)0)->parameter==248?1:-1];
typedef char check_context[(unsigned long)&((View *)0)->context==304?1:-1];
typedef char check_state[(unsigned long)&((View *)0)->state==778?1:-1];
typedef char check_visible[(unsigned long)&((View *)0)->visible==860?1:-1];
extern "C" {extern int mode_at(void);extern void begin_at(void),end_at(void),translate_at(const Vector3 *),angle_at(int,unsigned int),transform_at(void *),simple_at(void *),complex_at(void *,void *,float);
void draw_context_actor(View *o) {o->visible=o->visible_at(400.0f,20.0f);if(o->visible==1) {begin_at();translate_at(&o->position);angle_at(0,o->angle);transform_at(o->transform);if(mode_at()==1) simple_at(o->resource);else complex_at(o->resource,o->context,o->parameter);end_at();}}
}
