#include "src/include/hierarchy_root.h"
extern void init_at(RootNode *,RootNode *);
extern void *heap_new_at(unsigned int);
extern void heap_init_at(void *,unsigned int,int);
extern void *alloc_at(void *,unsigned int);
extern void *heap_0;
extern void *heap_1;
extern RootNode *root_child_0;
extern RootNode *root_child_1;
extern RootNode *root_child_2;
extern RootNode *root_child_3;
extern RootNode *root_child_4;
extern RootNode *root_child_5;
extern RootNode *root_child_6;
extern RootNode *root_child_7;
extern RootNode *root_child_8;
extern RootNode *root_child_9;
extern const char *root_name_0;
extern const char *root_name_1;
extern const char *root_name_2;
extern const char *root_name_3;
extern const char *root_name_4;
extern const char *root_name_5;
extern const char *root_name_6;
extern const char *root_name_7;
extern const char *root_name_8;
extern const char *root_name_9;
extern const char *root_name_10;
RootNode *initialize_hierarchy_root(RootNode *node) {
 RootNode **home=&node;

 RootNode *child;
 init_at(node,0);
 node->dispatch=(void *)0x8c261564;
 node->name=root_name_0;
 node->field_1e=32;
 { void *heap;
 heap=heap_new_at(12);
 if(heap) heap_init_at(heap,0x60000,16);
 heap_0=heap;
 }
 { void *heap;
 heap=heap_new_at(12);
 if(heap) heap_init_at(heap,0x10000,16);
 heap_1=heap; }
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_0=child;
 child->name=root_name_1;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_1=child;
 child->name=root_name_2;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_2=child;
 child->name=root_name_3;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_3=child;
 child->name=root_name_4;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_4=child;
 child->name=root_name_5;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_5=child;
 child->name=root_name_6;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_6=child;
 child->name=root_name_7;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_7=child;
 child->name=root_name_8;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_8=child;
 child->name=root_name_9;
 child=alloc_at(heap_0,32);
 if(child) init_at(child,node);
 root_child_9=child;
 child->name=root_name_10;
 return node;
}
