typedef struct View {char unknown0[4];unsigned short state;char unknown6[30];int timer;char unknown40[12];unsigned int flags;float target0,target1,target2,target3,current0,current1,current2,current3;unsigned int steps;float scale;char unknown96[4];int elapsed;} View;
typedef char check_state[(unsigned long)&((View *)0)->state==4?1:-1];
typedef char check_timer[(unsigned long)&((View *)0)->timer==36?1:-1];
typedef char check_flags[(unsigned long)&((View *)0)->flags==52?1:-1];
typedef char check_target0[(unsigned long)&((View *)0)->target0==56?1:-1];
typedef char check_target1[(unsigned long)&((View *)0)->target1==60?1:-1];
typedef char check_target2[(unsigned long)&((View *)0)->target2==64?1:-1];
typedef char check_target3[(unsigned long)&((View *)0)->target3==68?1:-1];
typedef char check_current0[(unsigned long)&((View *)0)->current0==72?1:-1];
typedef char check_current1[(unsigned long)&((View *)0)->current1==76?1:-1];
typedef char check_current2[(unsigned long)&((View *)0)->current2==80?1:-1];
typedef char check_current3[(unsigned long)&((View *)0)->current3==84?1:-1];
typedef char check_steps[(unsigned long)&((View *)0)->steps==88?1:-1];
typedef char check_scale[(unsigned long)&((View *)0)->scale==92?1:-1];
typedef char check_elapsed[(unsigned long)&((View *)0)->elapsed==100?1:-1];
typedef struct Quad {float x0,y0,x1,y1,u0,v0,u1,v1;} Quad;typedef struct Render {char unknown0[32];float origin_x,origin_y,scale_x,scale_y;int texture;float depth;} Render;typedef char check_quad[sizeof(Quad)==32?1:-1];
typedef char check_Quad_x0[(unsigned long)&((Quad *)0)->x0==0?1:-1];
typedef char check_Quad_y0[(unsigned long)&((Quad *)0)->y0==4?1:-1];
typedef char check_Quad_x1[(unsigned long)&((Quad *)0)->x1==8?1:-1];
typedef char check_Quad_y1[(unsigned long)&((Quad *)0)->y1==12?1:-1];
typedef char check_Quad_u0[(unsigned long)&((Quad *)0)->u0==16?1:-1];
typedef char check_Quad_v0[(unsigned long)&((Quad *)0)->v0==20?1:-1];
typedef char check_Quad_u1[(unsigned long)&((Quad *)0)->u1==24?1:-1];
typedef char check_Quad_v1[(unsigned long)&((Quad *)0)->v1==28?1:-1];
typedef char check_Render_origin_x[(unsigned long)&((Render *)0)->origin_x==32?1:-1];
typedef char check_Render_origin_y[(unsigned long)&((Render *)0)->origin_y==36?1:-1];
typedef char check_Render_scale_x[(unsigned long)&((Render *)0)->scale_x==40?1:-1];
typedef char check_Render_scale_y[(unsigned long)&((Render *)0)->scale_y==44?1:-1];
typedef char check_Render_texture[(unsigned long)&((Render *)0)->texture==48?1:-1];
typedef char check_Render_depth[(unsigned long)&((Render *)0)->depth==52?1:-1];
extern void *transform;extern void begin_at(int),transform_at(void *),mode_at(int,int),draw_at(View *,Quad *,Render *),end_at(void);
static inline void transform_y(Quad *q,Render *p) {q->y0=p->origin_y+(q->y0-p->origin_y)*p->scale_y;q->y1=p->origin_y+(q->y1-p->origin_y)*p->scale_y;}
void draw_view_border(View *o,Render *p) {Quad q;int height;float remaining,cap;if(p->texture<0) return;begin_at(1);transform_at(transform);mode_at(1,-1);height=(int)o->current3;height+=(4-(height&3))&3;cap=(float)height;if(cap<64.0f) cap*=0.5f;else cap=32.0f;q.y0=o->current1;q.y1=o->current1+cap;q.v0=0.0f;q.v1=cap/256.0f;transform_y(&q,p);draw_at(o,&q,p);q.y0=o->current1+(float)height-cap;q.y1=o->current1+(float)height;q.v0=(96.0f-cap)/256.0f;q.v1=0.375f;transform_y(&q,p);draw_at(o,&q,p);remaining=(float)height-64.0f;q.y0=o->current1+32.0f;q.v0=0.125f;q.v1=0.25f;q.y0=p->origin_y+(q.y0-p->origin_y)*p->scale_y;cap=p->scale_y*32.0f;while(!(remaining<0.0f)) {if(remaining<32.0f) {q.v1=(remaining+32.0f)/256.0f;cap=remaining*p->scale_y;}q.y1=q.y0+cap;draw_at(o,&q,p);q.y0+=cap;remaining-=32.0f;}end_at();}
