#include "src/include/vector3.h"
typedef struct Quad { float a; float b; float c; float d; } Quad;
typedef char check_Quad_a[(unsigned long)&((Quad *)0)->a==0?1:-1];
typedef char check_Quad_b[(unsigned long)&((Quad *)0)->b==4?1:-1];
typedef char check_Quad_c[(unsigned long)&((Quad *)0)->c==8?1:-1];
typedef char check_Quad_d[(unsigned long)&((Quad *)0)->d==12?1:-1];
typedef char check_Quad_prefix[sizeof(Quad)==16?1:-1];
typedef struct Counted { char unknown0[4]; unsigned int count; } Counted;
typedef char check_Counted_count[(unsigned long)&((Counted *)0)->count==4?1:-1];
typedef char check_Counted_prefix[sizeof(Counted)==8?1:-1];
typedef struct First { char unknown0[40]; void * data; void * other; } First;
typedef char check_First_data[(unsigned long)&((First *)0)->data==40?1:-1];
typedef char check_First_other[(unsigned long)&((First *)0)->other==44?1:-1];
typedef char check_First_prefix[sizeof(First)==48?1:-1];
typedef struct Second { char unknown0[20]; Counted * data; } Second;
typedef char check_Second_data[(unsigned long)&((Second *)0)->data==20?1:-1];
typedef char check_Second_prefix[sizeof(Second)==24?1:-1];
typedef struct Owner { char unknown0[1068]; First * first; Second * second; } Owner;
typedef char check_Owner_first[(unsigned long)&((Owner *)0)->first==1068?1:-1];
typedef char check_Owner_second[(unsigned long)&((Owner *)0)->second==1072?1:-1];
typedef char check_Owner_prefix[sizeof(Owner)==1076?1:-1];
typedef struct View { void * name; char unknown4[20]; void * dispatch; char unknown28[2]; short kind; char unknown32[8]; void * other; char unknown44[12]; void * data; char unknown60[48]; Vector3 zero; char unknown120[28]; Counted * resource; float last; float step; float current; Quad quad; unsigned int state_a; unsigned int state_b; Vector3 position; void * parameter; float strength; unsigned int color; } View;
typedef char check_View_name[(unsigned long)&((View *)0)->name==0?1:-1];
typedef char check_View_dispatch[(unsigned long)&((View *)0)->dispatch==24?1:-1];
typedef char check_View_kind[(unsigned long)&((View *)0)->kind==30?1:-1];
typedef char check_View_other[(unsigned long)&((View *)0)->other==40?1:-1];
typedef char check_View_data[(unsigned long)&((View *)0)->data==56?1:-1];
typedef char check_View_zero[(unsigned long)&((View *)0)->zero==108?1:-1];
typedef char check_View_resource[(unsigned long)&((View *)0)->resource==148?1:-1];
typedef char check_View_last[(unsigned long)&((View *)0)->last==152?1:-1];
typedef char check_View_step[(unsigned long)&((View *)0)->step==156?1:-1];
typedef char check_View_current[(unsigned long)&((View *)0)->current==160?1:-1];
typedef char check_View_quad[(unsigned long)&((View *)0)->quad==164?1:-1];
typedef char check_View_state_a[(unsigned long)&((View *)0)->state_a==180?1:-1];
typedef char check_View_state_b[(unsigned long)&((View *)0)->state_b==184?1:-1];
typedef char check_View_position[(unsigned long)&((View *)0)->position==188?1:-1];
typedef char check_View_parameter[(unsigned long)&((View *)0)->parameter==200?1:-1];
typedef char check_View_strength[(unsigned long)&((View *)0)->strength==204?1:-1];
typedef char check_View_color[(unsigned long)&((View *)0)->color==208?1:-1];
typedef char check_View_prefix[sizeof(View)==212?1:-1];
extern void base_at(View *,void *);
extern void *object_name;
extern Owner *resource_owner;
extern const Quad templates[];
View *initialize_template_position(View *o,void *parent,int index,const Vector3 *position,void *parameter) {
 base_at(o,parent); o->dispatch=(void *)0x8c26e4a8; o->name=object_name; o->kind=212;
 o->data=resource_owner->first->data;
 o->resource=resource_owner->second->data;
 o->current=0.0f;
 o->last=(float)o->resource->count-1.0f;
 o->step=0.1f;
 o->other=resource_owner->first->other;
 o->zero.x=0.0f; o->zero.y=0.0f; o->zero.z=0.0f;
 o->quad=*(const Quad *)((const char *)templates+((unsigned int)index<<4));
 o->position=*position;
 o->state_a=0; o->state_b=0;
 o->parameter=parameter;
 o->strength=0.04f;
 o->color=0xffffff;
 return o;
}
