struct Vector { float x, y, z; };
struct Record { char unknown0[16]; float height; };
struct Resource { char unknown0[8]; void *model, *transform; };
struct Owner { char unknown0[1068]; Resource *resource; void *auxiliary; };
struct Base {
    void *name;
    char unknown4[20];
    virtual void unused0();
    virtual void unused1();
    virtual void unused2();
    virtual void unused3();
    virtual void unused4();
    virtual void unused5();
    virtual void unused6();
    virtual void unused7();
    virtual void unused8();
    virtual void unused9();
    virtual void unused10();
    virtual void unused11();
    virtual void unused12();
    virtual void unused13();
    virtual void unused14();
    virtual void unused15();
    virtual void unused16();
    virtual void unused17();
    virtual void unused18();
    virtual void unused19();
    virtual void unused20();
    virtual void unused21();
    virtual void unused22();
    virtual void unused23();
    virtual void unused24();
    virtual void unused25();
    virtual void unused26();
    virtual void unused27();
    virtual void unused28();
    virtual void unused29();
    virtual void unused30();
    virtual void unused31();
    virtual void unused32();
    virtual void unused33();
    virtual void unused34();
    virtual void unused35();
    virtual void unused36();
    virtual void unused37();
    virtual void unused38();
    virtual void unused39();
    virtual void unused40();
    virtual void unused41();
    virtual void unused42();
    virtual void unused43();
    virtual void unused44();
    virtual void unused45();
    virtual void unused46();
    virtual void unused47();
    virtual void unused48();
    virtual void unused49();
    virtual void unused50();
    virtual void unused51();
    virtual void unused52();
    virtual void unused53();
    virtual void unused54();
    virtual void unused55();
    virtual void unused56();
    virtual void unused57();
    virtual void unused58();
    virtual void unused59();
    virtual void unused60();
    virtual void unused61();
    virtual void unused62();
    virtual void unused63();
    virtual void unused64();
    virtual void unused65();
    virtual void unused66();
    virtual void unused67();
    virtual void unused68();
    virtual void unused69();
    virtual void unused70();
    virtual void unused71();
    virtual void unused72();
    virtual void unused73();
    virtual void unused74();
    virtual void unused75();
    virtual void unused76();
    virtual void unused77();
    virtual void unused78();
    virtual void unused79();
    virtual void unused80();
    virtual void unused81();
    virtual void unused82();
    virtual void unused83();
    virtual void unused84();
    virtual void unused85();
    virtual void unused86();
    virtual void unused87();
    virtual void configure(void *);
};
struct View : Base {
    char unknown28[2];
    unsigned short size;
    char unknown32[20];
    unsigned int flags;
    char unknown56[4];
    Vector position;
    char unknown72[732];
    Vector saved_position;
    char unknown816[92];
    int kind;
    int counter;
    char unknown916[4];
    int state;
    int current;
    unsigned short slots[16];
    int last;
};
typedef char check_size[(unsigned long)&((View *)0)->size == 30 ? 1 : -1];
typedef char check_flags[(unsigned long)&((View *)0)->flags == 52 ? 1 : -1];
typedef char check_position[(unsigned long)&((View *)0)->position == 60 ? 1 : -1];
typedef char check_saved_position[(unsigned long)&((View *)0)->saved_position == 804 ? 1 : -1];
typedef char check_kind[(unsigned long)&((View *)0)->kind == 908 ? 1 : -1];
typedef char check_counter[(unsigned long)&((View *)0)->counter == 912 ? 1 : -1];
typedef char check_state[(unsigned long)&((View *)0)->state == 920 ? 1 : -1];
typedef char check_current[(unsigned long)&((View *)0)->current == 924 ? 1 : -1];
typedef char check_slots[(unsigned long)&((View *)0)->slots == 928 ? 1 : -1];
typedef char check_last[(unsigned long)&((View *)0)->last == 960 ? 1 : -1];
typedef char check_size[sizeof(View) == 964 && sizeof(Base) == 28 ? 1 : -1];
extern "C" {
    extern void *object_name;
    void base_at(View *, void *);
    void finish_at(View *);
}
extern "C" View *initialize_slot_actor(View *o, void *parent, void *parameter) {
    View **home = &o;
    base_at(o, parent);
    *(void **)((char *)o + 24) = (void *)0x8c263fc0;
    o->name = object_name;
    o->size = 964;
    o->configure(parameter);
    finish_at(o);
    o->saved_position = o->position;
    o->flags |= 0x06000800;
    o->counter = 0;
    o->kind = 34;
    o->current = -1;
    o->state = 0;
    for (int i = 0; i < 16; ++i)
        *(unsigned short *)((char *)o->slots + ((unsigned int)i << 1)) = 65535;
    o->last = -1;
    return o;
}
