typedef struct View {
    void * name;
    char unknown4[20];
    void * dispatch;
    char unknown28[2];
    unsigned short size;
    char unknown32[20];
    unsigned int flags;
    char unknown56[160];
    int mode;
    char unknown220[558];
    unsigned short state;
    char unknown780[104];
    float parameter0;
    float parameter1;
    float parameter2;
    float parameter3;
    char unknown900[32];
    int counter;
    int enabled;
    int active;
    int special;
    float distance;
    float radius;
    int value0;
    int value1;
    int value3;
    int value2;
    int first;
    int second;
} View;
typedef char check_name[(unsigned long)&((View *)0)->name == 0 ? 1 : -1];
typedef char check_dispatch[(unsigned long)&((View *)0)->dispatch == 24 ? 1 : -1];
typedef char check_size[(unsigned long)&((View *)0)->size == 30 ? 1 : -1];
typedef char check_flags[(unsigned long)&((View *)0)->flags == 52 ? 1 : -1];
typedef char check_mode[(unsigned long)&((View *)0)->mode == 216 ? 1 : -1];
typedef char check_state[(unsigned long)&((View *)0)->state == 778 ? 1 : -1];
typedef char check_parameter0[(unsigned long)&((View *)0)->parameter0 == 884 ? 1 : -1];
typedef char check_parameter1[(unsigned long)&((View *)0)->parameter1 == 888 ? 1 : -1];
typedef char check_parameter2[(unsigned long)&((View *)0)->parameter2 == 892 ? 1 : -1];
typedef char check_parameter3[(unsigned long)&((View *)0)->parameter3 == 896 ? 1 : -1];
typedef char check_counter[(unsigned long)&((View *)0)->counter == 932 ? 1 : -1];
typedef char check_enabled[(unsigned long)&((View *)0)->enabled == 936 ? 1 : -1];
typedef char check_active[(unsigned long)&((View *)0)->active == 940 ? 1 : -1];
typedef char check_special[(unsigned long)&((View *)0)->special == 944 ? 1 : -1];
typedef char check_distance[(unsigned long)&((View *)0)->distance == 948 ? 1 : -1];
typedef char check_radius[(unsigned long)&((View *)0)->radius == 952 ? 1 : -1];
typedef char check_value0[(unsigned long)&((View *)0)->value0 == 956 ? 1 : -1];
typedef char check_value1[(unsigned long)&((View *)0)->value1 == 960 ? 1 : -1];
typedef char check_value3[(unsigned long)&((View *)0)->value3 == 964 ? 1 : -1];
typedef char check_value2[(unsigned long)&((View *)0)->value2 == 968 ? 1 : -1];
typedef char check_first[(unsigned long)&((View *)0)->first == 972 ? 1 : -1];
typedef char check_second[(unsigned long)&((View *)0)->second == 976 ? 1 : -1];
typedef char check_size[sizeof(View) == 980 ? 1 : -1];
extern void *object_name;
extern void base_at(View *, void *);
extern int area_at(void);
View *initialize_parameter_actor(View *o, void *parent) {
    View **home = &o;
    base_at(o, parent);
    o->dispatch = (void *)0x8c26b174;
    o->name = object_name;
    o->size = 980;
    o->counter = 0;
    o->active = 1;
    switch (area_at()) {
    case 15: o->special = 1; break;
    default: o->special = 0; break;
    }
    o->state = 0;
    o->flags = 0x44000000;
    o->enabled = 0;
    if (!(o->parameter0 < 1000.0f)) {
        o->enabled = 1;
        o->value0 = (int)(o->parameter0 - 1000.0f);
    } else o->value0 = (int)o->parameter0;
    if (!(o->parameter1 < 1000.0f)) {
        o->enabled = 1;
        o->value1 = (int)(o->parameter1 - 1000.0f);
    } else o->value1 = (int)o->parameter1;
    o->value3 = (int)o->parameter3;
    o->value2 = (int)o->parameter2;
    o->distance = 400.0f;
    o->radius = 20.0f;
    o->mode = 2;
    o->first = 0;
    o->second = 0;
    return o;
}
