struct Vector { float x, y, z; };
struct Record { char unknown0[16]; float height; };
struct Resource { char unknown0[8]; void *model, *transform; };
struct Owner { char unknown0[1068]; Resource *resource; void *auxiliary; };
struct Base {
    void *name;
    char unknown4[20];
    virtual void unused0();
    virtual void unused1();
    virtual void unused2();
    virtual void unused3();
    virtual void unused4();
    virtual void unused5();
    virtual void unused6();
    virtual void unused7();
    virtual void unused8();
    virtual void unused9();
    virtual void unused10();
    virtual void unused11();
    virtual void unused12();
    virtual void unused13();
    virtual void unused14();
    virtual void unused15();
    virtual void unused16();
    virtual void unused17();
    virtual void unused18();
    virtual void unused19();
    virtual void unused20();
    virtual void unused21();
    virtual void unused22();
    virtual void unused23();
    virtual void unused24();
    virtual void unused25();
    virtual void unused26();
    virtual void unused27();
    virtual void unused28();
    virtual void unused29();
    virtual void unused30();
    virtual void unused31();
    virtual void unused32();
    virtual void unused33();
    virtual void unused34();
    virtual void unused35();
    virtual void unused36();
    virtual void unused37();
    virtual void unused38();
    virtual void unused39();
    virtual void unused40();
    virtual void unused41();
    virtual void unused42();
    virtual void unused43();
    virtual void unused44();
    virtual void unused45();
    virtual void unused46();
    virtual void unused47();
    virtual void unused48();
    virtual void unused49();
    virtual void unused50();
    virtual void unused51();
    virtual void unused52();
    virtual void unused53();
    virtual void unused54();
    virtual void unused55();
    virtual void unused56();
    virtual void unused57();
    virtual void unused58();
    virtual void unused59();
    virtual void unused60();
    virtual void unused61();
    virtual void unused62();
    virtual void unused63();
    virtual void unused64();
    virtual void unused65();
    virtual void unused66();
    virtual void unused67();
    virtual void unused68();
    virtual void unused69();
    virtual void unused70();
    virtual void unused71();
    virtual void unused72();
    virtual void unused73();
    virtual void unused74();
    virtual void unused75();
    virtual void unused76();
    virtual void unused77();
    virtual void unused78();
    virtual void unused79();
    virtual void unused80();
    virtual void unused81();
    virtual void unused82();
    virtual void unused83();
    virtual void unused84();
    virtual void unused85();
    virtual void unused86();
    virtual void unused87();
    virtual void configure(void *);
    virtual void unused89();
    virtual void unused90();
    virtual void unused91();
    virtual void unused92();
    virtual void set_mode(int, int);
};
struct View : Base {
    char unknown28[2];
    unsigned short size;
    char unknown32[8];
    void * transform;
    char unknown44[12];
    void * resource;
    Vector position;
    Vector previous;
    char unknown84[36];
    Vector origin;
    char unknown132[108];
    short state;
    char unknown242[102];
    Vector anchor;
    Vector destination;
    char unknown368[20];
    Record * record;
    char unknown392[412];
    Vector saved_position;
    char unknown816[60];
    void * profile;
    char unknown880[100];
};
typedef char check_size[(unsigned long)&((View *)0)->size == 30 ? 1 : -1];
typedef char check_transform[(unsigned long)&((View *)0)->transform == 40 ? 1 : -1];
typedef char check_resource[(unsigned long)&((View *)0)->resource == 56 ? 1 : -1];
typedef char check_position[(unsigned long)&((View *)0)->position == 60 ? 1 : -1];
typedef char check_previous[(unsigned long)&((View *)0)->previous == 72 ? 1 : -1];
typedef char check_origin[(unsigned long)&((View *)0)->origin == 120 ? 1 : -1];
typedef char check_state[(unsigned long)&((View *)0)->state == 240 ? 1 : -1];
typedef char check_anchor[(unsigned long)&((View *)0)->anchor == 344 ? 1 : -1];
typedef char check_destination[(unsigned long)&((View *)0)->destination == 356 ? 1 : -1];
typedef char check_record[(unsigned long)&((View *)0)->record == 388 ? 1 : -1];
typedef char check_saved_position[(unsigned long)&((View *)0)->saved_position == 804 ? 1 : -1];
typedef char check_profile[(unsigned long)&((View *)0)->profile == 876 ? 1 : -1];
typedef char check_sizes[sizeof(Base) == 28 && sizeof(View) == 980 && sizeof(Vector) == 12 ? 1 : -1];
typedef char check_owner[(unsigned long)&((Owner *)0)->resource == 1068 && (unsigned long)&((Owner *)0)->auxiliary == 1072 ? 1 : -1];
typedef char check_resource[(unsigned long)&((Resource *)0)->model == 8 && (unsigned long)&((Resource *)0)->transform == 12 ? 1 : -1];
typedef char check_record[(unsigned long)&((Record *)0)->height == 16 ? 1 : -1];
extern "C" {
    extern void *object_name;
    extern Owner *owner;
    extern char descriptor[], profile[], geometry[], parameters[];
    void base_at(View *, void *);
    void bind_at(View *, void *, void *, short);
    void geometry_at(View *, void *);
    void set_at(View *, void *, int);
    void finish_at(View *);
}
extern "C" View *initialize_anchor_actor_8c177ae4(View *o, void *parent, void *parameter) {
    View **home = &o;
    base_at(o, parent);
    *(void **)((char *)o + 24) = (void *)0x8c2709a0;
    o->name = object_name;
    o->size = 980;
    o->configure(parameter);
    {
        const Vector *p = &o->position;
        Vector *destination = &o->destination;
        *destination = *p;
        o->anchor = *p;
        *destination = *p;
        o->previous = *p;
    }
    o->set_mode(0, 1);
    o->resource = owner->resource->model;
    o->transform = owner->resource->transform;
    bind_at(o, descriptor, owner->auxiliary, o->state);
    o->profile = profile;
    geometry_at(o, geometry);
    set_at(o, parameters, 1);
    finish_at(o);
    o->saved_position = o->position;
    if (o->record)
        o->saved_position.y += o->record->height * 0.5f;
    o->origin = o->saved_position;
    return o;
}
