typedef struct Node {unsigned int flags;char unknown4[4];float x,y,width,height;char unknown24[8];void *active;int value;} Node;
typedef struct Pair {unsigned int flags;int remaining;} Pair;
typedef struct View {char unknown0[48];Node **nodes;unsigned int flags;char unknown56[24];float current2,current3;char unknown88[12];unsigned int field100;char unknown104[20];float offset;int first,selected,ttl;float next;Pair *pairs;float target;int insert,capacity;} View;
typedef char check_size_Node[sizeof(Node)==40?1:-1];
typedef char check_Node_flags[(unsigned long)&((Node *)0)->flags==0?1:-1];
typedef char check_Node_x[(unsigned long)&((Node *)0)->x==8?1:-1];
typedef char check_Node_y[(unsigned long)&((Node *)0)->y==12?1:-1];
typedef char check_Node_width[(unsigned long)&((Node *)0)->width==16?1:-1];
typedef char check_Node_height[(unsigned long)&((Node *)0)->height==20?1:-1];
typedef char check_Node_active[(unsigned long)&((Node *)0)->active==32?1:-1];
typedef char check_Node_value[(unsigned long)&((Node *)0)->value==36?1:-1];
typedef char check_size_Pair[sizeof(Pair)==8?1:-1];
typedef char check_Pair_flags[(unsigned long)&((Pair *)0)->flags==0?1:-1];
typedef char check_Pair_remaining[(unsigned long)&((Pair *)0)->remaining==4?1:-1];
typedef char check_size_View[sizeof(View)==160?1:-1];
typedef char check_View_nodes[(unsigned long)&((View *)0)->nodes==48?1:-1];
typedef char check_View_flags[(unsigned long)&((View *)0)->flags==52?1:-1];
typedef char check_View_current2[(unsigned long)&((View *)0)->current2==80?1:-1];
typedef char check_View_current3[(unsigned long)&((View *)0)->current3==84?1:-1];
typedef char check_View_field100[(unsigned long)&((View *)0)->field100==100?1:-1];
typedef char check_View_offset[(unsigned long)&((View *)0)->offset==124?1:-1];
typedef char check_View_first[(unsigned long)&((View *)0)->first==128?1:-1];
typedef char check_View_selected[(unsigned long)&((View *)0)->selected==132?1:-1];
typedef char check_View_ttl[(unsigned long)&((View *)0)->ttl==136?1:-1];
typedef char check_View_next[(unsigned long)&((View *)0)->next==140?1:-1];
typedef char check_View_pairs[(unsigned long)&((View *)0)->pairs==144?1:-1];
typedef char check_View_target[(unsigned long)&((View *)0)->target==148?1:-1];
typedef char check_View_insert[(unsigned long)&((View *)0)->insert==152?1:-1];
typedef char check_View_capacity[(unsigned long)&((View *)0)->capacity==156?1:-1];
extern void remove_at(View *,Node *),text_at(Node *,void *,int),width_at(Node *,float);
int insert_pair_grid_node(View *o,void *text,unsigned int flags,int value) {Node *node;Pair *pair;float width;if(!text) return 0;node=(*(Node **)(((unsigned int)o->insert<<2)+(char *)o->nodes));pair=(Pair *)((char *)o->pairs+((unsigned int)o->insert<<3));if(node->active) remove_at(o,node);if(flags&128) o->next=o->offset;if(flags&16) {float lower=o->offset+o->current3-26.0f;if(lower>o->next) o->next=lower;}if(flags&8) {if(o->selected==o->insert) flags&=~8;else node->flags|=8;}node->y=o->next;node->value=value;if(flags&2) text_at(node,text,32);else text_at(node,text,0);if(flags&32) node->flags|=1;if(flags&64) node->flags|=64;if(flags&256) node->flags|=128;width=o->current2-18.0f;if(o->flags&128) width-=15.0f;width_at(node,width);if(flags&512) node->x=width-node->width;else node->x=0.0f;pair->flags=flags;pair->remaining=o->ttl;if(++o->insert>=o->capacity) o->insert=0;o->next+=node->height+2.0f;if(flags&1) o->target=o->next-node->height-2.0f;else {float height=o->current3;if(o->next>o->offset+height-26.0f) {float target=o->next-(height-26.0f);if(target>o->target) o->target=target;}}return 1;}
