typedef struct TimeView {unsigned int words[3];} TimeView;
typedef struct Settings {int first,second,third,fourth,fifth,sixth,seventh,eighth;} Settings;
typedef char check_time_size[sizeof(TimeView)==12?1:-1];
typedef char check_setting_first[(unsigned long)&((Settings *)0)->first==0?1:-1];
typedef char check_setting_second[(unsigned long)&((Settings *)0)->second==4?1:-1];
typedef char check_setting_third[(unsigned long)&((Settings *)0)->third==8?1:-1];
typedef char check_setting_fourth[(unsigned long)&((Settings *)0)->fourth==12?1:-1];
typedef char check_setting_fifth[(unsigned long)&((Settings *)0)->fifth==16?1:-1];
typedef char check_setting_sixth[(unsigned long)&((Settings *)0)->sixth==20?1:-1];
typedef char check_setting_seventh[(unsigned long)&((Settings *)0)->seventh==24?1:-1];
typedef char check_setting_eighth[(unsigned long)&((Settings *)0)->eighth==28?1:-1];
extern void call_8c01c2b0(void);
extern void call_8c172be4(void);
extern void call_8c01d9dc(void);
extern void call_8c01c1c4(void);
extern void call_8c104e8c(void);
extern void call_8c1a18b8(void);
extern void call_8c0405b4(void);
extern void call_8c189c94(void);
extern void call_8c1a9940(void);
extern void call_8c0ea6d8(void);
extern void call_8c180ae8(void);
extern void call_8c0ea724(void);
extern void call_8c189d60(void);
extern void call_8c017ba8(void);
extern void call_8c13f3f0(void);
extern void call_8c017bd4(void);
extern void call_8c380516(void);
extern void begin_at(int,int,int);
extern void set_mode_at(int);
extern void set_phase_at(int);
extern void load_at(void *,int);
extern void configure_at(int,void *);
extern void * allocate_at(void *,unsigned int);
extern void initialize_large_at(void *,void *);
extern void * lookup_at(void);
extern int state_at(void *);
extern void request_at(int);
extern int time_ready_at(void);
extern void time_read_at(TimeView *);
extern void time_convert_at(TimeView *,unsigned int *);
extern void time_set_at(unsigned int);
extern void initialize_small_at(void *,void *);
extern void initialize_other_at(void *,void *);
extern void apply_settings_at(Settings *);
extern void prepare_global_at(void *);
extern void finish_small_at(void *);
extern void * existing;
extern void * heap;
extern void * parent;
extern void * selected;
extern int setting_mode;
extern int setting_state;
extern int reset_first;
extern int reset_second;
extern int reset_third;
extern Settings settings;
extern char load_data[];
extern char configuration[];
extern char global_storage[];
typedef struct Temporary {unsigned int words[8];} Temporary;
typedef char check_temporary[sizeof(Temporary)==32?1:-1];
extern void call_8c01ba00(void);
extern void call_8c02a798(void);
extern void call_8c1004cc(void);
extern void call_8c041690(void);
extern void call_8c01b7e8(void);
extern void call_8c1156b4(void);
extern void call_8c1a9988(void);
extern void call_8c186b34(void);
extern void call_8c09d2bc(void);
extern void call_8c17771c(void);
extern void call_8c115bc0(void);
extern void call_8c01ba20(void);
extern void call_8c02a87c(void);
extern void base_at(Temporary *,void *);
extern void load_resource_at(void *,unsigned int);
extern void prepare_at(void *);
extern void clear_at(void *);
extern void clear_settings_at(Settings *);
extern void mode_at(int);
extern void notify_at(int);
extern void destroy_at(Temporary *,int);
extern unsigned int resource_id;
extern char resource_data[];
extern int clear_value;
extern int parameter;
void reset_scene_transition(void) {Temporary temporary;base_at(&temporary,0);call_8c01ba00();call_8c017ba8();call_8c02a798();call_8c1004cc();call_8c041690();call_8c01d9dc();call_8c01b7e8();call_8c380516();call_8c380516();load_resource_at(resource_data,resource_id);call_8c1156b4();prepare_at(global_storage);clear_at(global_storage);clear_settings_at(&settings);clear_value=0;call_8c1a9988();call_8c186b34();call_8c09d2bc();call_8c13f3f0();call_8c01c2b0();call_8c1a18b8();call_8c0405b4();mode_at(2);configure_at(15,configuration);
 settings.second=15;settings.third=16;settings.fourth=16;{int value=parameter;settings.fifth=value;settings.sixth=0;settings.seventh=0;settings.first=-1;settings.eighth=0;settings.fourth=0;setting_mode=15;setting_state=value;}apply_settings_at(&settings);
 call_8c189d60();prepare_global_at(global_storage);call_8c17771c();call_8c115bc0();call_8c017bd4();call_8c01ba20();call_8c02a87c();notify_at(parameter);reset_second=0;destroy_at(&temporary,-1);
}
