#!/usr/bin/env python3
"""Report exact image coverage from a source-bound local verification checkpoint."""
import argparse
from datetime import date
import json
from pathlib import Path
import subprocess
import sys

import project
from matching import FLAGS, dependencies, sha

ROOT = Path(__file__).resolve().parents[1]


def read(root, name):
    return json.loads((root / name).read_text())


def inputs(root, manifest):
    names = {'config/project.json', 'config/decoded.json', 'config/samples.json',
             'config/matching-packages.json', 'config/compiler-packages.json',
             'tools/matching.py', 'tools/project.py', 'tools/verify_source.py', 'pso.py'}
    for unit in manifest['units']:
        names.add(unit['source'])
        names.update(dependencies(root / unit['source'], unit, root))
    return {name: sha(root / name) for name in sorted(names)}


def summary(root=ROOT):
    manifest = read(root, 'config/project.json')
    decoded = read(root, 'config/decoded.json')
    proof = read(root, 'config/progress-proof.json')
    if proof['inputs_sha256'] != inputs(root, manifest):
        raise ValueError('Progress checkpoint is stale; reproduce exact verification and use --record')
    if proof['flags'] != FLAGS or proof['integrated_image_sha256'] != decoded['sha256']:
        raise ValueError('Verification compiler settings or reference changed')
    required = {'two_fresh_exact_builds', 'integrated_image_exact', 'five_function_compiler_proof'}
    if not required <= set(proof['checks']):
        raise ValueError('Incomplete exact-build verification')
    spans = project.layout(manifest, decoded['size'])
    matched = sum(s['size'] for s in spans if s['origin'] == 'compiled_source')
    functions = 0
    addresses = set()
    for unit in manifest['units']:
        start = int(unit['address'], 0)
        end = start + unit['ranges'][0]['size']
        cursor = start
        for func in sorted(unit['functions'], key=lambda f: int(f['address'], 0)):
            address = int(func['address'], 0)
            if address != cursor or func['size'] <= 0 or address in addresses:
                raise ValueError('Invalid or duplicate function coverage')
            addresses.add(address)
            cursor = address + func['size']
            functions += 1
        if cursor != end:
            raise ValueError('Functions do not cover the admitted module')
    retained = decoded['size'] - matched
    if proof['source_only_rejected_retained_bytes'] != retained:
        raise ValueError('Stale reference-gap evidence')
    return {'schema_version': 1, 'version': 'pal', 'status': 'hybrid_reconstruction',
            'verification_date': proof['verification_date'], 'matching_functions': functions,
            'matching_modules': len(manifest['units']), 'compiled_range_bytes': matched,
            'decoded_image_bytes': decoded['size'], 'retained_reference_bytes': retained,
            'image_coverage_percent': round(100 * matched / decoded['size'], 8),
            'standalone_reconstructed_data_bytes': 0, 'code_completion_percent': None,
            'total_functions': None, 'source_only_build_available': retained == 0,
            'integrated_image_sha256': decoded['sha256'],
            'metric': 'Complete compiled function ranges, including literals and padding, divided by the entire decoded image. Not a code-only completion percentage.',
            'verification': 'Locally verified exact builds; CI validates the recorded input hashes and progress accounting.'}


def render(report):
    n, total, left = (report[k] for k in ['compiled_range_bytes', 'decoded_image_bytes', 'retained_reference_bytes'])
    pct = f"{report['image_coverage_percent']:.4f}%"
    md = f'''# Verified reconstruction progress

| Measure | Value |
| --- | ---: |
| Exact matching functions | {report['matching_functions']} |
| Matching modules | {report['matching_modules']} |
| Compiled complete ranges | {n:,} bytes |
| Decoded executable | {total:,} bytes |
| Image coverage | {pct} |
| Retained reference dependence | {left:,} bytes |
| Separately reconstructed static data | 0 bytes |
| Code-only completion percentage | Unknown |
| Total game function count | Unknown |
| Source-only build | Unavailable |

Complete ranges include literals and padding. Image coverage is **not** the
percentage of game code decompiled. Unmatched candidates earn no completed-byte
credit. The integrated hybrid image matches the reference, but still requires
{left:,} original bytes.

Exact-build verification recorded: **{report['verification_date']}**. Two fresh
project builds, exact integrated-image comparison and the five-function compiler
proof passed. Public CI checks the source-bound checkpoint and host-tool tests;
it does not access a game dump or recompile the game.

Generated by `python3 -B tools/progress.py` from the matching manifest and
`config/progress-proof.json`. Use `--check` to detect stale inputs or generated
reports. After new local exact verification, maintainers use `--record` to bind a
new checkpoint. See [BUILDING.md](BUILDING.md) and [TRACKER.md](TRACKER.md).
'''
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="230" height="20" role="img" aria-label="Image coverage: {pct}"><title>Image coverage: {pct} (includes literals and padding)</title><rect width="145" height="20" fill="#555"/><rect x="145" width="85" height="20" fill="#176b91"/><g fill="#fff" font-family="Verdana,sans-serif" font-size="11" text-anchor="middle"><text x="72" y="14">image byte coverage</text><text x="187" y="14">{pct}</text></g></svg>\n'''
    return {'progress.json': json.dumps(report, indent=2) + '\n', 'docs/PROGRESS.md': md, 'docs/progress.svg': svg}


def record(root=ROOT):
    subprocess.run([sys.executable, '-B', str(root / 'tools/verify_source.py'), '--check'], cwd=root, check=True)
    manifest = read(root, 'config/project.json')
    proof = read(root, 'config/source-validation.json')
    decoded = read(root, 'config/decoded.json')
    spans = project.layout(manifest, decoded['size'])
    retained = sum(s['size'] for s in spans if s['origin'] == 'reference_unreconstructed')
    if retained:
        try:
            project.require_source_coverage(spans)
        except ValueError:
            pass
        else:
            raise ValueError('Source-only build did not reject remaining reference gaps')
    tc = read(root, 'config/toolchain.json')
    result = {'schema_version': 1, 'verification_date': date.today().isoformat(),
              'checks': proof['checks'], 'inputs_sha256': inputs(root, manifest),
              'compiler': tc['compiler'], 'flags': tc['flags'],
              'integrated_image_sha256': decoded['sha256'],
              'source_only_build_available': retained == 0,
              'source_only_rejected_retained_bytes': retained,
              'provenance_note': 'Portable summary of local exact-build verification. CI checks source hashes and accounting; it does not rebuild the game or access private reference files.'}
    (root / 'config/progress-proof.json').write_text(json.dumps(result, indent=2) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--record', action='store_true', help='Record current verified local build evidence')
    args = parser.parse_args()
    if args.record:
        record()
    report = summary()
    for name, contents in render(report).items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != contents:
                raise ValueError('Generated progress is stale: ' + name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
    print(f"{report['matching_functions']} exact functions; {report['compiled_range_bytes']:,}/{report['decoded_image_bytes']:,} image bytes ({report['image_coverage_percent']:.4f}%).")


if __name__ == '__main__':
    try:
        main()
    except (OSError, ValueError, KeyError) as e:
        sys.exit(str(e))
