#ifndef PSO_SPAWN_EFFECT_H
#define PSO_SPAWN_EFFECT_H
/* Provisional views from raw initializer/constructor accesses.
 * Unknown bytes and untouched fields retain reference behavior. */
typedef struct SpawnResourceView {
 unsigned char unknown_00[0x14];
 void * field_14;
 float field_18;
 float field_1c;
 float field_20;
 float field_24;
 float field_28;
 unsigned char unknown_2c[0x4];
 float field_30;
 unsigned char unknown_34[0x4];
 float field_38;
 unsigned char unknown_3c[0xc];
 int field_48;
 int field_4c;
 unsigned char unknown_50[0x8];
 float field_58;
 float field_5c;
 unsigned char unknown_60[0x28];
 unsigned char field_88;
} SpawnResourceView;
typedef char check_SpawnResourceView_14[((unsigned long)&((SpawnResourceView *)0)->field_14)==0x14?1:-1];
typedef char check_SpawnResourceView_18[((unsigned long)&((SpawnResourceView *)0)->field_18)==0x18?1:-1];
typedef char check_SpawnResourceView_1c[((unsigned long)&((SpawnResourceView *)0)->field_1c)==0x1c?1:-1];
typedef char check_SpawnResourceView_20[((unsigned long)&((SpawnResourceView *)0)->field_20)==0x20?1:-1];
typedef char check_SpawnResourceView_24[((unsigned long)&((SpawnResourceView *)0)->field_24)==0x24?1:-1];
typedef char check_SpawnResourceView_28[((unsigned long)&((SpawnResourceView *)0)->field_28)==0x28?1:-1];
typedef char check_SpawnResourceView_30[((unsigned long)&((SpawnResourceView *)0)->field_30)==0x30?1:-1];
typedef char check_SpawnResourceView_38[((unsigned long)&((SpawnResourceView *)0)->field_38)==0x38?1:-1];
typedef char check_SpawnResourceView_48[((unsigned long)&((SpawnResourceView *)0)->field_48)==0x48?1:-1];
typedef char check_SpawnResourceView_4c[((unsigned long)&((SpawnResourceView *)0)->field_4c)==0x4c?1:-1];
typedef char check_SpawnResourceView_58[((unsigned long)&((SpawnResourceView *)0)->field_58)==0x58?1:-1];
typedef char check_SpawnResourceView_5c[((unsigned long)&((SpawnResourceView *)0)->field_5c)==0x5c?1:-1];
typedef char check_SpawnResourceView_88[((unsigned long)&((SpawnResourceView *)0)->field_88)==0x88?1:-1];
typedef struct SpawnEffect {
 unsigned char unknown_00[0x18];
 void * field_18;
 unsigned char unknown_1c[0x4];
 unsigned short field_20;
 unsigned char unknown_22[0x2];
 SpawnResourceView * field_24;
 unsigned short field_28;
 unsigned short field_2a;
 float field_2c;
 float field_30;
 float field_34;
 float field_38;
 float field_3c;
 float field_40;
 float field_44;
 float field_48;
 float field_4c;
 float field_50;
 float field_54;
 float field_58;
 float field_5c;
 int field_60;
 float field_64;
 float field_68;
 float field_6c;
 float field_70;
 float field_74;
 float field_78;
 float field_7c;
 float field_80;
 int field_84;
 unsigned char field_88;
 unsigned char field_89;
 unsigned short field_8a;
 int field_8c;
 int field_90;
 int field_94;
 float field_98;
 float field_9c;
} SpawnEffect;
typedef char check_SpawnEffect_18[((unsigned long)&((SpawnEffect *)0)->field_18)==0x18?1:-1];
typedef char check_SpawnEffect_20[((unsigned long)&((SpawnEffect *)0)->field_20)==0x20?1:-1];
typedef char check_SpawnEffect_24[((unsigned long)&((SpawnEffect *)0)->field_24)==0x24?1:-1];
typedef char check_SpawnEffect_28[((unsigned long)&((SpawnEffect *)0)->field_28)==0x28?1:-1];
typedef char check_SpawnEffect_2a[((unsigned long)&((SpawnEffect *)0)->field_2a)==0x2a?1:-1];
typedef char check_SpawnEffect_2c[((unsigned long)&((SpawnEffect *)0)->field_2c)==0x2c?1:-1];
typedef char check_SpawnEffect_30[((unsigned long)&((SpawnEffect *)0)->field_30)==0x30?1:-1];
typedef char check_SpawnEffect_34[((unsigned long)&((SpawnEffect *)0)->field_34)==0x34?1:-1];
typedef char check_SpawnEffect_38[((unsigned long)&((SpawnEffect *)0)->field_38)==0x38?1:-1];
typedef char check_SpawnEffect_3c[((unsigned long)&((SpawnEffect *)0)->field_3c)==0x3c?1:-1];
typedef char check_SpawnEffect_40[((unsigned long)&((SpawnEffect *)0)->field_40)==0x40?1:-1];
typedef char check_SpawnEffect_44[((unsigned long)&((SpawnEffect *)0)->field_44)==0x44?1:-1];
typedef char check_SpawnEffect_48[((unsigned long)&((SpawnEffect *)0)->field_48)==0x48?1:-1];
typedef char check_SpawnEffect_4c[((unsigned long)&((SpawnEffect *)0)->field_4c)==0x4c?1:-1];
typedef char check_SpawnEffect_50[((unsigned long)&((SpawnEffect *)0)->field_50)==0x50?1:-1];
typedef char check_SpawnEffect_54[((unsigned long)&((SpawnEffect *)0)->field_54)==0x54?1:-1];
typedef char check_SpawnEffect_58[((unsigned long)&((SpawnEffect *)0)->field_58)==0x58?1:-1];
typedef char check_SpawnEffect_5c[((unsigned long)&((SpawnEffect *)0)->field_5c)==0x5c?1:-1];
typedef char check_SpawnEffect_60[((unsigned long)&((SpawnEffect *)0)->field_60)==0x60?1:-1];
typedef char check_SpawnEffect_64[((unsigned long)&((SpawnEffect *)0)->field_64)==0x64?1:-1];
typedef char check_SpawnEffect_68[((unsigned long)&((SpawnEffect *)0)->field_68)==0x68?1:-1];
typedef char check_SpawnEffect_6c[((unsigned long)&((SpawnEffect *)0)->field_6c)==0x6c?1:-1];
typedef char check_SpawnEffect_70[((unsigned long)&((SpawnEffect *)0)->field_70)==0x70?1:-1];
typedef char check_SpawnEffect_74[((unsigned long)&((SpawnEffect *)0)->field_74)==0x74?1:-1];
typedef char check_SpawnEffect_78[((unsigned long)&((SpawnEffect *)0)->field_78)==0x78?1:-1];
typedef char check_SpawnEffect_7c[((unsigned long)&((SpawnEffect *)0)->field_7c)==0x7c?1:-1];
typedef char check_SpawnEffect_80[((unsigned long)&((SpawnEffect *)0)->field_80)==0x80?1:-1];
typedef char check_SpawnEffect_84[((unsigned long)&((SpawnEffect *)0)->field_84)==0x84?1:-1];
typedef char check_SpawnEffect_88[((unsigned long)&((SpawnEffect *)0)->field_88)==0x88?1:-1];
typedef char check_SpawnEffect_89[((unsigned long)&((SpawnEffect *)0)->field_89)==0x89?1:-1];
typedef char check_SpawnEffect_8a[((unsigned long)&((SpawnEffect *)0)->field_8a)==0x8a?1:-1];
typedef char check_SpawnEffect_8c[((unsigned long)&((SpawnEffect *)0)->field_8c)==0x8c?1:-1];
typedef char check_SpawnEffect_90[((unsigned long)&((SpawnEffect *)0)->field_90)==0x90?1:-1];
typedef char check_SpawnEffect_94[((unsigned long)&((SpawnEffect *)0)->field_94)==0x94?1:-1];
typedef char check_SpawnEffect_98[((unsigned long)&((SpawnEffect *)0)->field_98)==0x98?1:-1];
typedef char check_SpawnEffect_9c[((unsigned long)&((SpawnEffect *)0)->field_9c)==0x9c?1:-1];
typedef char check_spawn_effect_size[sizeof(SpawnEffect)==0xa0?1:-1];
#endif
